title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
google_analytics:
theme: minima

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
