title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
github: false
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
